services:
  vpn-bridge:
    image: alpine/socat
    container_name: vpn-bridge
    network_mode: host
    command:
      - "TCP-LISTEN:${LOCAL_PORT},bind=${DOCKER_BRIDGE_IP},reuseaddr,fork"
      - "TCP:${TARGET_IP}:${TARGET_PORT}"
    restart: unless-stopped
